//  DEVELOPMENT WEBPACK CONFIGURATION
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.common.js')({
  mode: 'development',
  entry: './app/index.tsx',
  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: '/',
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: '/index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],
  devtool: 'eval-source-map',
  devServer: {
    index: '/index.html',
    contentBase: [
      path.join(__dirname, 'assets/images'),
    ],
    hot: true,
    historyApiFallback: true,
    port: 3000,
  },
  performance: {
    hints: false,
  },
});

